#!/bin/sh
#
# @name Honeybee
#
# @type Quadrotor x
# @class Copter
#

sh /etc/init.d/rc.mc_defaults

param set BAT_N_CELLS 4
param set BAT_A_PER_V 36
param set BAT_V_DIV 18.1 

param set MIS_TAKEOFF_ALT 2.5

param set IMU_GYRO_CUTOFF 30.0
param set MC_DTERM_CUTOFF 0.0

param set MC_ROLL_P 2.2
param set MC_ROLLRATE_P 0.06
param set MC_ROLLRATE_I 0.2
param set MC_ROLLRATE_D 0.0017
param set MC_ROLLRATE_FF 0.0
param set MC_ROLLRATE_MAX 220.0
param set MC_ACRO_R_MAX 220.0

param set MC_PITCH_P 2.2
param set MC_PITCHRATE_P 0.06
param set MC_PITCHRATE_I 0.2
param set MC_PITCHRATE_D 0.0017
param set MC_PITCHRATE_FF 0.0
param set MC_PITCHRATE_MAX 220.0
param set MC_ACRO_P_MAX 220.0

param set MC_YAW_P 1
param set MC_YAWRATE_P 0.15
param set MC_YAWRATE_I 0.2
param set MC_YAWRATE_D 0
param set MC_YAWRATE_FF 0.0
param set MC_YAWRATE_MAX 200.0
param set MC_ACRO_Y_MAX 540.0
param set MPC_MAN_Y_MAX 200.0

param set MPC_TILTMAX_AIR 45.0
param set MPC_MAN_TILT_MAX 45.0

param set MPC_VELD_LP 5.0

param set MPC_XY_CRUISE 8.0
param set MPC_XY_VEL_MAX 8.0
param set MPC_Z_VEL_MAX_UP 8.0
param set MPC_Z_VEL_MAX_DN 2.0

param set MPC_XY_P 0.95
param set MPC_XY_VEL_P 0.09
param set MPC_XY_VEL_I 0.02
param set MPC_XY_VEL_D 0.01

param set MPC_Z_P 1.0
param set MPC_Z_VEL_P 0.2
param set MPC_Z_VEL_I 0.02
param set MPC_Z_VEL_D 0

param set PWM_MAX 1950
param set PWM_MIN 1000

param set MPC_THR_HOVER 0.27
param set MPC_THR_MAX 1.0
param set MPC_THR_MIN 0.02
param set MPC_MANTHR_MIN 0.02

param set RTL_DESCEND_ALT 10.0
param set RTL_RETURN_ALT 10.0

set MIXER quad_x
