#!/bin/sh
#
# @name Griffin
#
# @type Quadrotor x
# @class Copter
#

sh /etc/init.d/rc.mc_defaults

param set BAT_N_CELLS 6
param set BAT_A_PER_V 37.5
param set BAT_V_DIV 12.7
param set BAT_V_OFFS_CURR 0.525

param set MIS_TAKEOFF_ALT 2.5
param set RTL_DESCEND_ALT 10

param set IMU_GYRO_CUTOFF 80.0
param set MC_DTERM_CUTOFF 30.0

param set MC_ROLL_P 5
param set MC_ROLLRATE_P 0.2764
param set MC_ROLLRATE_I 0.0720
param set MC_ROLLRATE_D 0.0060
param set MC_ROLLRATE_FF 0.0
param set MC_ROLLRATE_MAX 120.0
param set MC_ACRO_R_MAX 120.0

param set MC_PITCH_P 5
param set MC_PITCHRATE_P 0.2764
param set MC_PITCHRATE_I 0.0720
param set MC_PITCHRATE_D 0.0060
param set MC_PITCHRATE_FF 0.0
param set MC_PITCHRATE_MAX 120.0
param set MC_ACRO_P_MAX 120.0

param set MC_YAW_P 0.8
param set MC_YAWRATE_P 0.3983
param set MC_YAWRATE_I 0.1593
param set MC_YAWRATE_D 0
param set MC_YAWRATE_FF 0.0
param set MC_YAWRATE_MAX 90.0
param set MC_ACRO_Y_MAX 45.0
param set MPC_MAN_Y_MAX 45.0

param set MPC_TILTMAX_AIR 30.0
param set MPC_MAN_TILT_MAX 30.0

param set MPC_VELD_LP 5.0

param set MPC_XY_CRUISE 12.0
param set MPC_XY_VEL_MAX 12.0

param set MPC_XY_P 0.73254
param set MPC_XY_VEL_P 0.1615
param set MPC_XY_VEL_I 0.0319
param set MPC_XY_VEL_D 0.0106

param set MPC_Z_P 1.0
param set MPC_Z_VEL_P 0.1549
param set MPC_Z_VEL_I 0.0279
param set MPC_Z_VEL_D 0

param set PWM_MAX 1670
param set PWM_MIN 1000

param set MPC_THR_HOVER 0.3515625
param set MPC_THR_MAX 1.0
param set MPC_THR_MIN 0.08
param set MPC_MANTHR_MIN 0.08

param set RTL_DESCEND_ALT 10.0
param set RTL_RETURN_ALT 10.0

param set PWM_MAIN_SCALE1 1.01315789
param set PWM_MAIN_SCALE2 1.00442478
param set PWM_MAIN_SCALE3 1.00074019
param set PWM_MAIN_SCALE4 1.00000000

set MIXER griffin
