#!/bin/sh
#
# @name Griffin
#
# @type Quadrotor x
# @class Copter
#

sh /etc/init.d/rc.mc_defaults

param set BAT_N_CELLS 6
param set BAT_A_PER_V 37.5
param set BAT_V_DIV 12.7
param set BAT_V_OFFS_CURR 0.525

param set IMU_GYRO_CUTOFF 30.0
param set IMU_ACCEL_CUTOFF 30.0
param set MC_DTERM_CUTOFF 0.0

param set MC_ROLL_P 3
param set MC_ROLLRATE_P 0.0842
param set MC_ROLLRATE_I 0.0196
param set MC_ROLLRATE_D 0.0029
param set MC_ROLLRATE_FF 0.0
param set MC_ROLLRATE_MAX 120.0
param set MC_ACRO_R_MAX 120.0

param set MC_PITCH_P 3
param set MC_PITCHRATE_P 0.086
param set MC_PITCHRATE_I 0.020
param set MC_PITCHRATE_D 0.003
param set MC_PITCHRATE_FF 0.0
param set MC_PITCHRATE_MAX 120.0
param set MC_ACRO_P_MAX 120.0

param set MC_YAW_P 1.2
param set MC_YAWRATE_P 0.35
param set MC_YAWRATE_I 0.03
param set MC_YAWRATE_D 0
param set MC_YAWRATE_FF 0.0
param set MC_YAWRATE_MAX 45.0
param set MC_ACRO_Y_MAX 45.0
param set MPC_MAN_Y_MAX 45.0

param set MPC_TILTMAX_AIR 30.0
param set MPC_MAN_TILT_MAX 30.0

param set MPC_VELD_LP 5.0

param set MPC_XY_P 0.35
param set MPC_XY_VEL_P 0.048
param set MPC_XY_VEL_I 0.008
param set MPC_XY_VEL_D 0.002

param set MPC_Z_P 0.9
param set MPC_Z_VEL_P 0.1
param set MPC_Z_VEL_I 0.01
param set MPC_Z_VEL_D 0

param set MPC_XY_CRUISE 12.0
param set MPC_XY_VEL_MAX 12.0
param set MPC_VEL_MANUAL 12.0
param set MPC_Z_VEL_MAX_DN 1.0
param set MPC_Z_VEL_MAX_UP 3.0

param set MIS_TAKEOFF_ALT 20
param set RTL_DESCEND_ALT 10.0
param set RTL_RETURN_ALT 10.0
param set MPC_TKO_RAMP_T 0.0
param set MPC_TKO_SPEED 3.0

param set COM_OBL_ACT 2
param set COM_OBL_RC_ACT 5

param set PWM_MAX 1850
param set PWM_MIN 1000

param set MPC_THR_CURVE 1
param set MPC_THR_HOVER 0.35
param set MPC_THR_MAX 1.0
param set MPC_THR_MIN 0.1
param set MPC_MANTHR_MIN 0.1

set MIXER griffin
set PWM_OUT 12345678
